var fecha = new Date()
console.log("El año es: "+fecha.getFullYear())
console.log("El mes es: "+fecha.getMonth())
console.log("El día es: "+fecha.getDate())
console.log("Los minutos es: "+fecha.getMinutes())
console.log("El segundo es: "+fecha.getSeconds())